/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   mapTest.cpp                                        :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: hdrabi <hdrabi@student.42.fr>              +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2022/07/14 12:05:19 by hdrabi            #+#    #+#             */
/*   Updated: 2022/07/16 12:47:19 by hdrabi           ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include <iostream>
#include <map>
#include <iterator>
#include "./map/map.hpp"


int main() {
    
    std::cout << "****************** test 0 < constructors , iterators > ******************" << std::endl;
    {
        try
        {

        }
        catch(const std::exception& e)
        {
            std::cerr << e.what() << '\n';
        }
        std::cout << "----------------------------------------" << std::endl;
        try
        {


        }
        catch(const std::exception& e)
        {
            std::cerr << e.what() << '\n';
        }
        
    }

    std::cout << std::endl << "****************** test 0 < constructors , iterators > ******************" << std::endl;
    {
        try
        {

        }
        catch(const std::exception& e)
        {
            std::cerr << e.what() << '\n';
        }
        std::cout << "----------------------------------------" << std::endl;
        try
        {
            

        }
        catch(const std::exception& e)
        {
            std::cerr << e.what() << '\n';
        }
    }

    std::cout << std::endl << "****************** test 0 < constructors , iterators > ******************" << std::endl;
    {
        try
        {
            

        }
        catch(const std::exception& e)
        {
            std::cerr << e.what() << '\n';
        }
        std::cout << "----------------------------------------" << std::endl;
        try
        {
            

        }
        catch(const std::exception& e)
        {
            std::cerr << e.what() << '\n';
        }
    }

    std::cout << std::endl << "****************** test 0 < constructors , iterators > ******************" << std::endl;
    {
        try
        {
            

        }
        catch(const std::exception& e)
        {
            std::cerr << e.what() << '\n';
        }
        std::cout << "----------------------------------------" << std::endl;
        try
        {
            

        }
        catch(const std::exception& e)
        {
            std::cerr << e.what() << '\n';
        }
    }

    std::cout << std::endl << "****************** test 0 < constructors , iterators > ******************" << std::endl;
    {
        try
        {
            

        }
        catch(const std::exception& e)
        {
            std::cerr << e.what() << '\n';
        }
        std::cout << "----------------------------------------" << std::endl;
        try
        {
            

        }
        catch(const std::exception& e)
        {
            std::cerr << e.what() << '\n';
        }
    }

    std::cout << std::endl << "****************** test 0 < constructors , iterators > ******************" << std::endl;
    {
        try
        {
            

        }
        catch(const std::exception& e)
        {
            std::cerr << e.what() << '\n';
        }
        std::cout << "----------------------------------------" << std::endl;
        try
        {
            

        }
        catch(const std::exception& e)
        {
            std::cerr << e.what() << '\n';
        }
    }

    std::cout << std::endl << "****************** test 0 < constructors , iterators > ******************" << std::endl;
    {
        try
        {
            

        }
        catch(const std::exception& e)
        {
            std::cerr << e.what() << '\n';
        }
        std::cout << "----------------------------------------" << std::endl;
        try
        {
            

        }
        catch(const std::exception& e)
        {
            std::cerr << e.what() << '\n';
        }
    }

    std::cout << std::endl << "****************** test 0 < constructors , iterators > ******************" << std::endl;
    {
        try
        {
            

        }
        catch(const std::exception& e)
        {
            std::cerr << e.what() << '\n';
        }
        std::cout << "----------------------------------------" << std::endl;
        try
        {
            

        }
        catch(const std::exception& e)
        {
            std::cerr << e.what() << '\n';
        }
    }
}